-- SCRIPT PACIENTES MÓDULO DE TRIAGE

-- Borrar tabla si existe
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE PACIENTES CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- Creación de la tabla pacientes
CREATE TABLE PACIENTES (
    ID                  NUMBER(19, 0) GENERATED BY DEFAULT AS IDENTITY,
    NOMBRE              VARCHAR2(100) NOT NULL,
    APELLIDO_PATERNO    VARCHAR2(100) NOT NULL,
    APELLIDO_MATERNO    VARCHAR2(100) NOT NULL,
    GRAVEDAD            NUMBER(1) NOT NULL,
    ACTIVO              NUMBER(1) DEFAULT 1 NOT NULL,
    
    
    CONSTRAINT PK_PACIENTES PRIMARY KEY (ID),
    CONSTRAINT CHK_PACIENTES_GRAVEDAD CHECK (GRAVEDAD BETWEEN 1 AND 5),
    CONSTRAINT CHK_PACIENTES_ACTIVO   CHECK (ACTIVO IN (0, 1))
);

-- 
COMMENT ON TABLE PACIENTES IS 'Tabla transaccional que gestiona los ingresos de la sala de espera en el módulo de Triage Clínico.';
COMMENT ON COLUMN PACIENTES.GRAVEDAD IS 'Escala de prioridad clínica acotada: 1 (Máxima gravedad) a 5 (Menor urgencia).';
COMMENT ON COLUMN PACIENTES.ACTIVO IS 'Mecanismo de ocultamiento lógico (Soft Delete): 1 = En sala de espera, 0 = Dado de alta.';


INSERT INTO PACIENTES (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, GRAVEDAD, ACTIVO)
VALUES ('Juan', 'Pérez', 'González', 1, 1);

INSERT INTO PACIENTES (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, GRAVEDAD, ACTIVO)
VALUES ('María', 'López', 'Rodríguez', 2, 1);

-- Pacientes No Críticos (Gravedad 3, 4 y 5): Permiten gestión de evolución clínica y alta
INSERT INTO PACIENTES (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, GRAVEDAD, ACTIVO)
VALUES ('Carlos', 'Soto', 'Muñoz', 3, 1);

INSERT INTO PACIENTES (NOMBRE, APELLIDO_PATERNO, APELLIDO_MATERNO, GRAVEDAD, ACTIVO)
VALUES ('Ana', 'Vargas', 'Herrera', 5, 1);

COMMIT;