name: Java CI con Maven

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar el repositorio
      uses: actions/checkout@v4

    - name: Configurar Java JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Evaluar API Camas
      run: mwb -f api-camas/pom.xml clean test
      continue-on-error: true

    - name: Evaluar API Triage
      run: mvn -f api-triage/pom.xml clean test
